export { default as SiteLayout } from "./views/site-layout";
export { default as HomeView, homeMetadata } from "./views/home-view";
export { CoursesRoute, coursesMetadata } from "./views/courses-view";
export { ArticlesRoute, articlesMetadata } from "./views/articles-view";
export { ARTICLE_SECTIONS } from "./config/routes";
export type { ArticleSectionKey } from "./config/routes";
export { TeachersRoute, teachersMetadata } from "./views/teachers-view";
export { default as ReviewsView, reviewsMetadata } from "./views/reviews-view";
export { AboutRoute, aboutMetadata, ContactView, contactMetadata } from "./views/about-view";
export { PolicyRoute, policyMetadata } from "./views/policy-view";
export { buildSitemap } from "./views/sitemap";
export { default as AppNotFound } from "./shared/app-not-found";
export { default as AppLoading } from "./shared/loading/app-loading";
